### ISSUE TITLE
Add support for dublin core metadata(DCMI)

### ISSUE THREAD

**Issue by BjBlazkowicz** [scrapinghub/extruct#10]
Often used to describe publications etc. More information:

http://dublincore.org/
https://en.wikipedia.org/wiki/Dublin_Core
http://dublincore.org/documents/dces/

**Comment by vu3jej** [comment]
I'd like to try this one if no one else is working on it right now :man_technologist:

**Comment by hbbtstar** [comment]
@vu3jej did you ever get a chance to get started on this? It would come in handy for us the next couple of months!

If you haven't, also happy to help out by submitting a PR- I'd have to build it in-house otherwise, always better to open-source!

**Comment by joaquingx** [comment]
As it seems that there's no progress yet, I would be happy to help here, I'll begin now! :muscle:
