### ISSUE TITLE
Accessing extracted data which is not unique

### ISSUE THREAD

**Issue by Chris8080** [scrapinghub/extruct#104]
Hello,

extruct is working very well for me use case and I get plenty of structured text out of websites.
I'm mostly using Microdata. 
Unfortunately, some websites seem to have different structures from others, so for example, sometimes I'd get an array:

`'brand': {'properties': {'name': 'NIKE'},
                                         'type': 'http://schema.org/Brand'},`

and sometimes a string:

`'brand': 'NIKE',`

So to access the data, I'd need to do something like:

`            if isinstance(productData['brand'], dict):
                if 'http://schema.org/Brand' == productData['brand']['type']:
                    self.brand = productData['brand']['properties']['name']
            if isinstance(productData['brand'], str):
                self.brand = productData['brand']`

Is this the best way to go or am I doing this in a clumsy way?

Thanks,
Chris

**Comment by lopuhin** [comment]
@Chris8080 I think that's the right way to do this, we're using a similar approach. You can also check out ``uniform=True`` option (https://github.com/scrapinghub/extruct#uniform) which makes output from different formats more structurally uniform without loosing information, but it still preserves distinctions which you want to remove here.

**Comment by Chris8080** [comment]
Ok, sounds good .. so at least I know I'm kind of on the right track.
`uniform=True` looks good, thanks - I'll use it.
