### ISSUE TITLE
RDFa ordering not preserved on duplicated properties

### ISSUE THREAD

**Issue by ivanprado** [scrapinghub/extruct#116]
When a property is repeated (i.e. on a page with multiple images annotates as `og:image`) RDFa return it as a list but is not preserving order. Preserving order is important as usually the first image is the most important. An example of page where this would be happening:

https://cleantechnica.com/2019/04/16/fukushimas-final-costs-will-approach-one-trillion-dollars-just-for-nuclear-disaster/

It seems difficult to solve it in extruct as the problem seems to present in `PyRdfa` library, and it is even happening in the online service: https://www.w3.org/2012/pyRdfa/Overview.html#distill_by_uri+with_options

Related with https://github.com/scrapinghub/extruct/pull/115 (I created an xfail test for that in this PR)

**Comment by kmike** [comment]
fwiw, extruct is using https://github.com/RDFLib/rdflib, not pyRdfa. This could be related (not 100% sure): https://github.com/RDFLib/rdflib/issues/538.

**Comment by croqaz** [comment]
What would be the implications to use SET instead or LIST in the RDFa values?
Eg: The values would be converted to sets of frozen Dicts:

```
"http://ogp.me/ns#image": [
                {
                    "@value": "http://images.sk-static.com/images/media/img/col4/20100330-103600-169450.jpg"
                },
                {
                    "@value": "http://images.sk-static.com/SECONDARY_IMAGE.jpg"
                }
            ],
```

**Comment by ivanprado** [comment]
@croqaz the order is important for values. Usually, some pages annotate several images but the most important one (the one with the biggest resolution or more relevant) is the first one. If a set is used the order is lost. Instead, it would better to get consistent ordering by having values in the order they appear in the page. That's unfortunately not the case for RDFa.

**Comment by croqaz** [comment]
Thank you for the explanation @ivanprado 👍

**Comment by adityas114** [comment]
Hi, I would like to work on this. It would be great if you can assign me the issue.

I am thinking when the parsed output is returned from rdflib in rdfa.py, we can use the document object to fix the order in extruct itself. I have started working on it and I can raise a pull request soon.

**Comment by ivanprado** [comment]
Hi @adityas114 . Nice if you can work on it :+1: . In order to contribute, just create a PR with the fix. There is no need to assign the issue.

**Comment by adityas114** [comment]
@ivanprado I have created a PR (#139) for this issue. Please have a look and let me know if it requires any changes.
