### ISSUE TITLE
First non-empty result should be extracted in case of OpenGraph

### ISSUE THREAD

**Issue by kmike** [scrapinghub/extruct#117]
https://github.com/scrapinghub/extruct/pull/115 was a step in a right direction (prefer first results), but it seems it is not the whole solution, as empty results should not be prioritized. 

E.g. on https://www.triganostore.com/tente-de-camping-raclet-bora-4.html there are two og:description values, the first one is empty. https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.triganostore.com%2Ftente-de-camping-raclet-bora-4.html shows that a non-empty one is extracted.

**Comment by ivanprado** [comment]
Proposed a fix here: https://github.com/scrapinghub/extruct/pull/121

**Comment by ivanprado** [comment]
Fixed on #121
