### ISSUE TITLE
constrains rdflib to 4.2.2?

### ISSUE THREAD

**Issue by teledyn** [scrapinghub/extruct#136]
extruct appears to be the only item in my scrapy installation that is still constraining to rdf 4.2.2 -- are there plans for an update?

**Comment by Gallaecio** [comment]
See #135

**Comment by lopuhin** [comment]
We want to lift this restriction but no concrete timeline yet, PRs are always welcome. I'll close this as a duplicate of #135 as @Gallaecio noted.
