### ISSUE TITLE
Ability to look up items by itemtype or itemprop

### ISSUE THREAD

**Issue by waqasshabbir** [scrapinghub/extruct#21]
In cases, when one is not interested in all but some parts of microdata, the approach to filter required content is not very straight forward. Can we support look-up by `itemtype` or `itemprop` values as follows:

```
>>> data = mde.extruct(html)
>>> data.get_first(itemprop='name')
'foo'
>>> data.get(itemtype='http://schema.org/Person')
[{'name': 'foo', 'jobTitle': 'bar', 'additionalName': 'foobar'}]
>>> data.get(itemtype='http://schema.org/Person', itemprop='name')
['foo', 'abc', 'cde', 'def']
>>> data.get(itemtype='http://schema.org/Organization', itemprop='name')
['foocompany']
```

or a cleaner version with some sort of built-in support for popular vocabularies.
```
>>> data.get(itemtype=schema_org.Person)
[{'name': 'foo', 'jobTitle': 'bar', 'additionalName': 'foobar'}, {'name': 'abc', ...}]
>>> data.get(itemtype=schema_org.Person', itemprop='name')
['foo', 'abc', 'cde', 'def']
>>> data.get_first(itemtype=schema_org.Organization, itemprop='name')
'foocompany'
```

**Comment by redapple** [comment]
@waqasshabbir , about
> the approach to filter required content is not very straight forward

what are you using?

I'm wondering if something like jmespath is not easier to work on the `{"items": []}` dict values

**Comment by waqasshabbir** [comment]
@redapple using `for`s and `if`s. 

P.S. TIL about jmespath. Closing the issue.
