### ISSUE TITLE
Package breaking due to change in lxml

### ISSUE THREAD

**Issue by marcosfelt** [scrapinghub/extruct#215]
With new versions of lxml (I believe above 5.1.0), this package breaks with the following error:

```bash
ImportError: cannot import name '_ElementStringResult' from 'lxml.etree' 
```

I think the temporary solution is to pin the lxml version `>=5.0.0,<5.1.0`. I'm happy to submit a pull request for this.

**Comment by PandaSanchez** [comment]
> With new versions of lxml (I believe above 5.1.0), this package breaks with the following error:
> 
> ```shell
> ImportError: cannot import name '_ElementStringResult' from 'lxml.etree' 
> ```
> 
> I think the temporary solution is to pin the lxml version `>=5.0.0,<5.1.0`. I'm happy to submit a pull request for this.

I also encountered this issue today and -- per @marcosfelt's recommendation -- pinning the lxml version fixed it. This saved the day for me, thanks!

**Comment by jayaddison** [comment]
@marcosfelt @honzajavorek please double-check before making any adjustments based on this, but I believe that it was v5.1.1 (not v5.1.0) of `lxml` that introduced the relevant breaking change (https://github.com/lxml/lxml/commit/eba79343d0e7ad1ce40169f60460cdd4caa29eb3).
