### ISSUE TITLE
Extract contents with tags

### ISSUE THREAD

**Issue by joke2k** [scrapinghub/extruct#22]
Hi, when I use extruct to extract some microdata from html element that contains some script or style tags I encountered some problems: tags are skipped out but theirs contents remains.

This behaviour is happened because `LxmlMicrodataExtractor.extract_textContent` uses  `lxml.html.tostring(node, method="text", encoding='unicode', with_tail=False)` with method "text".
Probably we have to add a parameter to allow using "html" method and maybe a way to use the lxml Cleaner (http://lxml.de/lxmlhtml.html#cleaning-up-html).

**Comment by redapple** [comment]
@joke2k , could you provide an example HTML snippet?

**Comment by redapple** [comment]
@joke2k , would https://github.com/scrapinghub/extruct/issues/23 work for you?

**Comment by redapple** [comment]
@joke2k , do you have any feedback on the proposed fix #23?
Thanks.
