### ISSUE TITLE
cannot import name '_ElementStringResult' from 'lxml.etree

### ISSUE THREAD

**Issue by williambarberjr** [scrapinghub/extruct#230]
If you just run:
`pip install extruct`

And then:
`import extruct`

You should get the error:
`cannot import name '_ElementStringResult' from 'lxml.etree`

Reverting to a previous version of lxml solves this:
`pip install lxml==5.1.0`

**Comment by tonal** [comment]
see #215

**Comment by williambarberjr** [comment]
Sorry about that, a quick search didn't pull that issue up for whatever reason
