### ISSUE TITLE
Nested lists returned by JsonLD extractor.

### ISSUE THREAD

**Issue by rolando** [scrapinghub/extruct#34]
See below, the output is a nested list rather than a list of dicts.

```
In [9]: url = 'http://www.superpages.com/yellowpages/c-nurseries/s-wa/t-redmond/'

In [10]: r = requests.get(url)

In [11]: ex = extruct.jsonld.JsonLdExtractor()

In [12]: ex.extract(r.text)['items']

[[{'@context': 'http://schema.org',
   '@type': 'LocalBusiness',
   'address': {'@type': 'PostalAddress',
    'addressLocality': 'Redmond',
    'addressRegion': 'WA',
    'postalCode': '98053',
    'streetAddress': '20871 NE Redmond Fall City Rd'},
   'description': "There's more to a beautiful garden than what meets the eye.",
   'name': 'Gray Barn Nursery',
   'telephone': '888-820-9506'},
    ...
]]
```

**Comment by redapple** [comment]
Thanks for reporting @rolando , makes sense to have a list of dicts as output.
(and [Google's testing tool](https://search.google.com/structured-data/testing-tool) does output multiple LocalBusinesses).
The specs are rather unclear (to me at least) as to how to serialize multiple objects, and what makes a JSON-LD object in this case.
(I cannot see examples of `<script type="application/ld+json">[{...},{...}]</script>` [in the specs](http://json-ld.org/spec/latest/json-ld))
I'll need to read them more carefully.

**Comment by rolando** [comment]
Hey @redapple, thanks for your input. I didn't notice the html source itself had the metadata defined as a list.

**Comment by redapple** [comment]
Alright, I think [I found it](http://json-ld.org/spec/latest/json-ld/#json-ld-grammar):

> A JSON-LD document must be valid JSON text as described in [RFC7159].
> A JSON-LD document must be a single node object or an array whose elements are each node objects at the top level.
