### ISSUE TITLE
Unable to read UTF-8

### ISSUE THREAD

**Issue by Gautamshahi** [scrapinghub/extruct#55]
The code is not able to read the UTF-8, where I can modify the code? The extruct supports only ASCII?

Error-

![image](https://user-images.githubusercontent.com/3966230/29924803-d547c3e0-8e7b-11e7-91a6-b14579e56987.png)

**Comment by redapple** [comment]
It's more likely about non-ASCII characters in your source `.py` file.
You should set your file encoding in the top part of your source files, e.g. `# -*- coding: utf-8 -*- ` if you use UTF-8

**Comment by redapple** [comment]
When reporting issues, please paste all relevant files regarding input data, source code, stack trace if any, actual result and expected results.
[StackOverflow](https://stackoverflow.com) is also a invaluable resource for these kind of issues (that are not extruct-specific), for example https://stackoverflow.com/questions/28898561/syntaxerror-non-ascii-character-xe3-in-file-g-test-py-on-line-2-but-no-enc
