### ISSUE TITLE
Adding headers in request

### ISSUE THREAD

**Issue by vaulstein** [scrapinghub/extruct#6]
Is there a way to pass headers and also set cookies in the request that is made?

**Comment by redapple** [comment]
@vaulstein , you mean when using the HTTP server? It's not possible with the current version.

At the moment the web service is very very basic and was not the focus of this first first release.
It's using python-requests() which allows to send anything, and should not be hard to patch.

The question is more about what API the service could expose.
Right now it accepts only the URL `/extruct/url`, which is simple enough from the browser URL bar.
Would you be using this in the browser or from the command line? (curl and the like)

**Comment by vaulstein** [comment]
@Paul: I would mostly be using it through command line. Since it is using
requests, I would try to patch it and maybe give a PR.

**Comment by vaulstein** [comment]
@redapple : Regarding adding headers, I was considering if a request using python's request module was made to :

/extruct/<URL> 
method = GET

/extruct/batch 
method = POST

extruct's get or post method

and headers/cookies were passed through the request, handling headers and cookies would be simpler

what do you think?

**Comment by redapple** [comment]
@vaulstein , so any headers passed to the endpoint would be sent as-is to the end website?
makes sense

**Comment by cathalgarvey** [comment]
It's my opinion, per #63, that we should actually remove server and client mode for `extruct` and leave those roles to other, better-suited third party tools. Just posting it here in case it's still of interest to anyone involved in this issue.

Because this issue is now quite stale, I'll close it; feel free to reopen if needed.
