### ISSUE TITLE
Add support for microformats

### ISSUE THREAD

**Issue by cathalgarvey** [scrapinghub/extruct#64]
Extruct ought to support [microformats](http://microformats.org/wiki/Microformats2).

**Comment by lopuhin** [comment]
@cathalgarvey could you please clarify which microformats do you mean or link to a spec?

**Comment by Kebniss** [comment]
I am working on a pull request that adds https://github.com/microformats/mf2py for microformat extraction

**Comment by cathalgarvey** [comment]
Indeed, those microformats! Thanks Ludovica. :)

On 21 March 2018 21:56:47 GMT+00:00, Ludovica Gonella <notifications@github.com> wrote:
>I am working on a pull request that adds
>https://github.com/microformats/mf2py for microformat extraction
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scrapinghub/extruct/issues/64#issuecomment-375109223

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Kebniss** [comment]
closing because feature was implemented

**Comment by cathalgarvey** [comment]
Awesome, thanks Ludovica! I think this merits a version bump.. :)

On 28 March 2018 20:19:47 GMT+01:00, Ludovica Gonella <notifications@github.com> wrote:
>closing because feature was implemented
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scrapinghub/extruct/issues/64#issuecomment-377004699

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Kebniss** [comment]
@cathalgarvey how can I do that? :)
