### ISSUE TITLE
Add support for Open Graph Arrays

### ISSUE THREAD

**Issue by jakubwasikowski** [scrapinghub/extruct#92]
It is possible in Open Graph Protocol to specify more than one value for a single property. It's called OG Array http://ogp.me/#array. 

It seems that currently `extruct` doesn't support arrays in case the `uniform` option is set to `True`, because `uniform._uopengraph` function doesn't handle duplicated keys from the list of properties.

It'd be cool to add that support and return list in case there is more than one value or to just add some separate property with `list` suffix to be backward compatible.

**Comment by ivanprado** [comment]
Same problem in my case. Open Graph with `uniform` avoids the possibility of extracting multiple images. Only last image is returned. Example:

```py
import pprint
import extruct
pp = pprint.PrettyPrinter(indent=2)

html = """<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="https://www.w3.org/1999/xhtml" xmlns:og="https://ogp.me/ns#" xmlns:fb="https://www.facebook.com/2008/fbml">
 <head>
  <title>Himanshu's Open Graph Protocol</title>
  <meta http-equiv="Content-Type" content="text/html;charset=WINDOWS-1252" />
  <meta http-equiv="Content-Language" content="en-us" />
  <link rel="stylesheet" type="text/css" href="event-education.css" />
  <meta name="verify-v1" content="so4y/3aLT7/7bUUB9f6iVXN0tv8upRwaccek7JKB1gs=" >
  <meta property="og:title" content="Himanshu's Open Graph Protocol"/>
  <meta property="og:type" content="article"/>
  <meta property="og:url" content="https://www.eventeducation.com/test.php"/>
  <meta property="og:image" content="https://www.eventeducation.com/images/1.jpg"/>
  <meta property="og:image:width" content="400" />
  <meta property="og:image" content="https://www.eventeducation.com/images/2.jpg"/>
  <meta property="og:image:width" content="500" />
  <meta property="fb:admins" content="himanshu160"/>
  <meta property="og:site_name" content="Event Education"/>
  <meta property="og:description" content="Event Education provides free courses on event planning and management to event professionals worldwide."/>
 </head>
 <body>
 </body>
</html>"""

pp.pprint(extruct.extract(html, uniform=True)['opengraph'])
```

result:

```py
[ { '@context': {'og': 'http://ogp.me/ns#'},
    '@type': 'article',
    'og:description': 'Event Education provides free courses on event planning '
                      'and management to event professionals worldwide.',
    'og:image': 'https://www.eventeducation.com/images/2.jpg',
    'og:image:width': '500',
    'og:site_name': 'Event Education',
    'og:title': "Himanshu's Open Graph Protocol",
    'og:url': 'https://www.eventeducation.com/test.php'}]
```

**Comment by Gallaecio** [comment]
If backward compatibility is to be kept, I’m not sure what the best approach would be.

**Comment by ragnerok** [comment]
Hi, I'd like to work on this issue. Can you assign this issue to me ?
    
One way to solve this issue while keeping it backward compatible is to add a flag with_og_array that returns an og_array if it is true.

**Comment by lopuhin** [comment]
> Hi, I'd like to work on this issue, can you assign it to me ?

Hi @ragnerok contributions are very welcome, I don't think anyone is working on this.

> One way to solve this issue while keeping it backward compatible is to add a flag with_og_array that returns an og_array if it is true.

Sounds good to me :+1:

**Comment by ragnerok** [comment]
Hey @lopuhin, I've added the changes that I think will fix the issue. Could you look into it and let me know if I need to change something else ? I'll add the test cases in some time.
