### ISSUE TITLE
I want to get only one type of schema.org annotation how can i do it 

### ISSUE THREAD

**Issue by juriigen** [scrapinghub/extruct#94]
i have this json but i want only the @type Product annotated not @type BreadcrumbList . Is there a way to get only Product ?
[
  {
    "@context": "http://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "item": {
          "@id": "https://concordpetfoods.com/collections",
          "name": "Collections"
        }
      },
      {
        "@type": "ListItem",
        "position": 2,
        "item": {
          "@id": "https://concordpetfoods.com/collections/dog",
          "name": "Dog"
        }
      },
      {
        "@type": "ListItem",
        "position": 3,
        "item": {
          "@id": "https://concordpetfoods.com/collections/dog/products/blue-buffalo-blue-wilderness-rocky-mountain-recipe-adult-healthy-weight-red-meat-dry-dog-food",
          "name": "Blue Buffalo BLUE Wilderness Rocky Mountain Recipe Adult Healthy Weight Red Meat Dry Dog Food"
        }
      }
    ]
  },
  {
    "@context": "http://schema.org/",
    "@type": "Product",
    "name": "Blue Buffalo BLUE Wilderness Rocky Mountain Recipe Adult Healthy Weight Red Meat Dry Dog Food",
    "image": "https://cdn.shopify.com/s/files/1/2382/0223/products/35913-1501600645_fc502f43-827d-4a76-a639-90c668e5e4bc_1024x1024.png?v=1533919507",
    "description": "<p>Looking for a great food to help your four legged best friend reach and maintain their ideal weight?  Blue Buffalo has got just the food for you with their BLUE Wilderness Rocky Mountain Recipe Adult Healthy Weight Red Meat Dry Dog Food!  This grain-free, protein-rich food contains the finest natural ingredients and provides multiple sources of protein using deboned beef, lamb and venison without the added calories!  Blue Buffalo BLUE Wilderness Rocky Mountain Recipe Adult Healthy Weight Red Meat Dry Dog Food also includes blueberries, cranberries and carrots to help support antioxidant-enrichment. Put on your spandex, Rover! Let’s get physical! </p><br><h3>Why We Love It</h3><ul>\n<li>100% grain-free</li>\n<li>No by-products, fillers, soy, corn, artificial preservatives, colors or flavors.</li>\n<li>Made in the USA</li>\n</ul><p><br></p><h3>About Blue Buffalo</h3><p>BLUE Buffalo's True Blue promise is the pillar of their business, straight to every customer; the finest natural ingredients, and no chicken/poultry by-product meals, corn, wheat, soy, artificial preservatives, colors or flavors. BLUE Buffalo is the only food made with unique Lifesource Bits; a precise blend of vitamins, minerals and antioxidants created by veterinarians and animal nutritionists. With recipes for all tastes and diets, including limited ingredient diets, high protein, grain-free, wholesome grains, and exotic proteins, BLUE Buffalo always starts with real meat, and ends with good health.</p><h2>Ingredients</h2>Deboned Beef, Chicken Meal, Pea Protein, Peas, Tapioca Starch, Pea Starch, Menhaden Fish Meal (source of Omega 3 Fatty Acids), Pea Fiber, Dried Tomato Pomace, Natural Flavor, Flaxseed (source of Omega 6 Fatty Acids), Chicken Fat (preserved with Mixed Tocopherols), Powdered Cellulose, Dehydrated Alfalfa Meal, DL-Methionine, Deboned Lamb, Deboned Venison, Dried Chicory Root, Choline Chloride, Potatoes, Calcium Carbonate, Caramel Color, Dicalcium Phosphate, preserved with Mixed Tocopherols, Sweet Potatoes, Carrots, L-Carnitine, Zinc Amino Acid Chelate, Zinc Sulfate, Salt, Potassium Chloride, Ferrous Sulfate, Vitamin E Supplement, Iron Amino Acid Chelate, Glucosamine Hydrochloride, Blueberries, Cranberries, Barley Grass, Parsley, Yucca Schidigera Extract, Dried Kelp, Turmeric, Nicotinic Acid (Vitamin B3), Calcium Pantothenate (Vitamin B5), L-Ascorbyl-2-Polyphosphate (source of Vitamin C), L-Lysine, Oil of Rosemary, Copper Sulfate, Biotin (Vitamin B7), Vitamin A Supplement, Copper Amino Acid Chelate, Manganese Sulfate, Taurine, Chondroitin Sulfate, Manganese Amino Acid Chelate, Thiamine Mononitrate (Vitamin B1), Riboflavin (Vitamin B2), Vitamin D3 Supplement, Vitamin B12 Supplement, Pyridoxine Hydrochloride (Vitamin B6), Calcium Iodate, Dried Yeast, Dried Enterococcus faecium fermentation product, Dried Lactobacillus acidophilus fermentation product, Dried Aspergillus niger fermentation extract, Dried Trichoderma longibrachiatum fermentation extract, Dried Bacillus subtilis fermentation extract, Folic Acid (Vitamin B9), Sodium Selenite.<br>\r\n<h2>Guaranteed Analysis</h2><table>\n<tr>\n<th>Nutrient</th>\n<th>Guaranteed Units</th>\n</tr>\n<tr>\n<td>Crude Protein</td>\n<td>30.0% min</td>\n</tr>\n<tr>\n<td>Crude Fat</td>\n<td>10% min</td>\n</tr>\n<tr>\n<td>Crude Fiber</td>\n<td>10.0% max</td>\n</tr>\n<tr>\n<td>Moisture</td>\n<td>10.0% max</td>\n</tr>\n<tr>\n<td>Calcium</td>\n<td>1.2% min</td>\n</tr>\n<tr>\n<td>Phosphorus</td>\n<td>0.9% min</td>\n</tr>\n<tr>\n<td>Omega-3 Fatty Acids</td>\n<td>0.5% min</td>\n</tr>\n<tr>\n<td>Omega-6 Fatty Acids</td>\n<td>1.5% min</td>\n</tr>\n<tr>\n<td>L-Carnitine</td>\n<td>150 mg/kg min</td>\n</tr>\n<tr>\n<td>Glucosamine</td>\n<td>400 mg/kg min</td>\n</tr>\n<tr>\n<td>Chondroitin Sulfate</td>\n<td>300 mg/kg min</td>\n</tr>\n</table>",
    "brand": {
      "@type": "Thing",
      "name": "Blue Buffalo"
    },
    "sku": "36492",
    "offers": {
      "@type": "Offer",
      "priceCurrency": "USD",
      "price": 65.99,
      "availability": "http://schema.org/InStock",
      "seller": {
        "@type": "Organization",
        "name": "Concord Pet Foods &amp; Supplies"
      }
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "WebSite",
    "name": "Concord Pet Foods &amp; Supplies",
    "url": "https://concordpetfoods.com"
  }
]

**Comment by Kebniss** [comment]
you cannot specify this when calling extruct but you can filter json-ld content after it is extracted:
```
filtered = []
for e in result['json-ld']:
    if e['@type'] == 'Product':
         filtered.append(e)
```

**Comment by juriigen** [comment]
@Kebniss  Thank you very much i am new in python 👍 
p.s you can close the "issue"

**Comment by Kebniss** [comment]
no problem, happy to help!
