### ISSUE TITLE
Dealing with Async loaded json-ld

### ISSUE THREAD

**Issue by omprakaash** [scrapinghub/extruct#98]
Hello! Is there a way to deal with async loaded json-ld such as in this url -> “https://www.omicsdi.org/dataset/arrayexpress-repository/E-GEOD-33515”

extruct “https://www.omicsdi.org/dataset/arrayexpress-repository/E-GEOD-33515” results in no json-ld metadata being returned

**Comment by lopuhin** [comment]
@omprakaash I think the only general way to solve this is to load the page in a headless browser (e.g. headless chrome or with http://splash.readthedocs.io), and then pass html after rendering to extruct. Another option, if you can trace which request fetches json-ld, you can fetch it directly and pass to extruct.

**Comment by omprakaash** [comment]
Ah. Thank you! Will try doing it the way you suggested.
